openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /select-reward:
    post:
      operationId: postSelectReward
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RewardSelection'
      responses:
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
    RewardSelection:
      required:
      - acceptedTnC
      - selectedRewardDealId
      - userId
      type: object
      properties:
        userId:
          type: string
        selectedRewardDealId:
          type: string
        acceptedTnC:
          type: boolean
      description: Represents selected reward.
